<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 STRICT//EN" "DTD/xhtml1-strict.dtd">
<html>
<head>
<title>RVD Field Processor</title>
<link href="/mchp.css" rel="stylesheet" type="text/css" />
<script src="/mchp.js" type="text/javascript"></script>
</head>

<body onLoad="allowAJAX=true;" onUnload="allowAJAX=false;">
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">

<div style="padding:0 0 5px 5px"><img src="/logo.GIF" /></div>

<div id="title"><div class="right">RVD Field Processor</div><span id="hello">&nbsp;</span></div>

<div id="menu">
<a href="/index.htm" onclick="allowAJAX=false;">Home</a>
<a href="/protect/control.htm" onclick="allowAJAX=false;">Relay Control</a>
<a href="/protect/ntpstatus.htm" onclick="allowAJAX=false;">NTP Status</a>
<a href="/protect/ntpconfig.htm" onclick="allowAJAX=false;">NTP Setting</a>
<a href="/protect/tcpip.htm" onclick="allowAJAX=false;">Ethernet Setting</a>
<a href="/protect/firmware.htm" onclick="allowAJAX=false;">Firmware</a>
<a href="/tech.htm" onclick="allowAJAX=false;">Support</a>

</div>